#!/bin/sh /etc/rc.common
# author: xiaofan <xfan1024@live.com>

START=35
STOP=85
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param command /usr/bin/dns-selector
	procd_close_instance
}

