#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
client="/usr/bin/kcptun-client"
server="/usr/bin/kcptun-server"

start_kcptun() {
	local cfg="$1"
	local bin="$2"
	local localaddr, remoteaddr, key, crypt, mode, conn, autoexpire, mtu, sndwnd, rcvwnd, nocomp, sockbuf, keepalive

	config_get localaddr $cfg localaddr
	config_get remoteaddr $cfg remoteaddr
	config_get key $cfg key
	config_get crypt $cfg crypt
	config_get mode $cfg mode
	config_get conn $cfg conn
	config_get autoexpire $cfg autoexpire
	config_get mtu $cfg mtu
	config_get sndwnd $cfg sndwnd
	config_get rcvwnd $cfg rcvwnd
	config_get_bool nocomp $cfg nocomp
	config_get sockbuf $cfg sockbuf
	config_get keepalive $cfg keepalive

	procd_open_instance
	procd_set_param command "$bin"
	[ -n "$localaddr" ] && procd_append_param command -l "$localaddr"
	[ -n "$remoteaddr" ] && procd_append_param command -r "$remoteaddr"
	[ -n "$key" ] && procd_append_param command --key "$key"
	[ -n "$crypt" ] && procd_append_param command --crypt "$crypt"
	[ -n "$mode" ] && procd_append_param command --mode "$mode"
	[ -n "$conn" ] && procd_append_param command --conn "$conn"
	[ -n "$autoexpire" ] && procd_append_param command --autoexpire "$autoexpire"
	[ -n "$mtu" ] && procd_append_param command --mtu "$mtu"
	[ -n "$sndwnd" ] && procd_append_param command --sndwnd "$sndwnd"
	[ -n "$rcvwnd" ] && procd_append_param command --rcvwnd "$rcvwnd"
	[ "$nocomp" = 1 ] && procd_append_param command --nocomp
	[ -n "$sockbuf" ] && procd_append_param command --sockbuf "$sockbuf"
	[ -n "$keepalive" ] && procd_append_param command --keepalive "$keepalive"
	procd_close_instance
}

start_service() {
	config_load kcptun
	[ -f "${client}" ] config_foreach start_kcptun client "${client}" 
	[ -f "${server}" ] config_foreach start_kcptun server "${server}"
}
