#!/bin/sh /etc/rc.common
# author: xiaofan <xfan1024@live.com>
. /usr/share/libubox/jshn.sh

START=80
USE_PROCD=1
client="/usr/bin/kcptun-client"
server="/usr/bin/kcptun-server"
confdir="/var/etc/kcptun"

start_kcptun() {
	local cfg="$1"
	local bin="$2"
	local confpath
	local localaddr remoteaddr key crypt mode conn autoexpire \
		mtu sndwnd rcvwnd nocomp sockbuf keepalive disabled

	config_get_bool disabled $cfg disabled
	[ "$disabled" = 1 ] && return

	confpath="$confdir/$cfg.json"
	mkdir -p "$confdir"

	config_get localaddr $cfg localaddr
	config_get remoteaddr $cfg remoteaddr
	config_get targetaddr $cfg targetaddr
	config_get key $cfg key
	config_get crypt $cfg crypt
	config_get mode $cfg mode
	config_get conn $cfg conn
	config_get autoexpire $cfg autoexpire
	config_get mtu $cfg mtu
	config_get sndwnd $cfg sndwnd
	config_get rcvwnd $cfg rcvwnd
	config_get_bool nocomp $cfg nocomp
	config_get sockbuf $cfg sockbuf
	config_get keepalive $cfg keepalive

	procd_open_instance
	procd_set_param command "$bin" -c "$confpath"
	json_init
	[ -n "$localaddr" ] && json_add_string "localaddr" "$localaddr"
	[ -n "$remoteaddr" ] && json_add_string "remoteaddr" "$remoteaddr"
	[ -n "$targetaddr" ] && json_add_string "targetaddr" "$targetaddr"
	[ -n "$key" ] && json_add_string "key" "$key"
	[ -n "$crypt" ] && json_add_string "crypt" "$crypt"
	[ -n "$mode" ] && json_add_string "mode" "$mode"
	[ -n "$conn" ] && json_add_int "conn" "$conn"
	[ -n "$autoexpire" ] && json_add_int "autoexpire" "$autoexpire"
	[ -n "$mtu" ] && json_add_int "mtu" "$mtu"
	[ -n "$sndwnd" ] && json_add_int "sndwnd" "$sndwnd"
	[ -n "$rcvwnd" ] && json_add_int "rcvwnd" "$rcvwnd"
	[ "$nocomp" = 1 ] && json_add_boolean "nocomp" "true"
	[ -n "$sockbuf" ] && json_add_int "sockbuf" "$sockbuf"
	[ -n "$keepalive" ] && json_add_int "keepalive" "$keepalive"
	json_close_object
	json_dump -i >"$confpath"
	procd_close_instance
}

start_service() {
	config_load kcptun
	[ -f "${client}" ] && config_foreach start_kcptun client "${client}"
	[ -f "${server}" ] && config_foreach start_kcptun server "${server}"
}
